import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from './assets/vite.svg'
import heroImg from './assets/hero.png'
import './App.css'
import DownloadButton from './components/atoms/download-button/DownloadButton'
import { PrimaryButton, SecondaryButton, LinkButton, Card } from './components/atoms'

function App() {
  const [count, setCount] = useState(0)

  return (
    <main>
      <h1>Emotion Design System — Demo</h1>
      <p>Click to download a sample file generated by the component.</p>
      <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start', flexWrap: 'wrap' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <PrimaryButton>Primary</PrimaryButton>
          <SecondaryButton>Secondary</SecondaryButton>
          <LinkButton>Link style</LinkButton>
        </div>

        <div style={{ display: 'flex', gap: 16, alignItems: 'flex-start', flex: 1 }}>
          <Card horizontal thumbnail={heroImg} title="Project Alpha" footer={<PrimaryButton size="sm">Open</PrimaryButton>}>
            A short description of Project Alpha. Uses design tokens for spacing and typography.
          </Card>

          <Card horizontal thumbnail={heroImg} title="Project Beta" footer={<SecondaryButton size="sm">Details</SecondaryButton>}>
            Project Beta has a different state and uses secondary actions.
          </Card>

          <Card horizontal thumbnail={heroImg} title="Project Gamma" footer={<LinkButton size="sm">Learn more</LinkButton>}>
            Project Gamma highlights the horizontal card layout.
          </Card>

          <div style={{ alignSelf: 'start' }}>
            <DownloadButton label="Download sample" filename="sample.txt" />
          </div>
        </div>
      </div>
    </main>
  )
}

export default App
