import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from './assets/vite.svg'
import heroImg from './assets/hero.png'
import './App.css'
import DownloadButton from './components/atoms/download-button/DownloadButton'
import { PrimaryButton, SecondaryButton, LinkButton } from './components/atoms'

function App() {
  const [count, setCount] = useState(0)

  return (
    <main>
      <h1>Emotion Design System — Demo</h1>
      <p>Click to download a sample file generated by the component.</p>
      <div style={{ display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
        <PrimaryButton>Primary</PrimaryButton>
        <SecondaryButton>Secondary</SecondaryButton>
        <LinkButton>Link style</LinkButton>
        <DownloadButton label="Download sample" filename="sample.txt" />
      </div>
    </main>
  )
}

export default App
